"""数据模块：全球市场股票、指数、基金数据源配置。

支持多个数据源的降级策略：
1. AKShare（主要，国内可用）
2. Yahoo Finance（海外备用）
3. Investing.com（补充数据源）
4. TradingView（参考数据源）
"""
from __future__ import annotations

from typing import Any

# 市场区域配置
MARKET_REGIONS = {
    "美洲市场": {
        "countries": ["美国", "加拿大", "巴西", "墨西哥"],
        "currencies": ["USD", "CAD", "BRL", "MXN"],
        "timezones": ["America/New_York", "America/Toronto", "America/Sao_Paulo"],
    },
    "欧洲市场": {
        "countries": ["英国", "德国", "法国", "瑞士", "意大利", "西班牙", "荷兰"],
        "currencies": ["GBP", "EUR", "CHF"],
        "timezones": ["Europe/London", "Europe/Berlin", "Europe/Paris", "Europe/Zurich"],
    },
    "亚洲市场": {
        "countries": ["中国", "日本", "韩国", "香港", "印度", "新加坡", "澳大利亚"],
        "currencies": ["CNY", "JPY", "KRW", "HKD", "INR", "SGD", "AUD"],
        "timezones": ["Asia/Shanghai", "Asia/Tokyo", "Asia/Seoul", "Asia/Hong_Kong", "Asia/Kolkata"],
    },
}

# 全球关键指数配置
GLOBAL_INDICES: dict[str, dict[str, Any]] = {
    # 美洲市场
    "SPX": {
        "name": "标普500",
        "market": "美股",
        "region": "美洲市场",
        "country": "美国",
        "currency": "USD",
        "description": "美股大盘指数",
        "default_pe": 22.0,
        "earnings_growth": 7.0,
        "asset_type": "index",
        "yahoo_symbol": "^GSPC",
        "ak_symbol": "标普500指数",
        "investing_symbol": "spx",
        "tv_symbol": "SPX500",
        "hot": True,
    },
    "NDX": {
        "name": "纳斯达克100",
        "market": "美股",
        "region": "美洲市场",
        "country": "美国",
        "currency": "USD",
        "description": "科技成长指数",
        "default_pe": 28.0,
        "earnings_growth": 10.0,
        "asset_type": "index",
        "yahoo_symbol": "^NDX",
        "ak_symbol": None,
        "investing_symbol": "nasdaq",
        "tv_symbol": "NAS100",
        "hot": True,
    },
    "DJI": {
        "name": "道琼斯工业指数",
        "market": "美股",
        "region": "美洲市场",
        "country": "美国",
        "currency": "USD",
        "description": "美国蓝筹指数",
        "default_pe": 20.0,
        "earnings_growth": 5.0,
        "asset_type": "index",
        "yahoo_symbol": "^DJI",
        "ak_symbol": None,
        "investing_symbol": "djia",
        "tv_symbol": "DJI",
        "hot": True,
    },
    "RUT": {
        "name": "罗素2000",
        "market": "美股",
        "region": "美洲市场",
        "country": "美国",
        "currency": "USD",
        "description": "美国小盘指数",
        "default_pe": 24.0,
        "earnings_growth": 6.0,
        "asset_type": "index",
        "yahoo_symbol": "^RUT",
        "ak_symbol": None,
        "investing_symbol": "rut",
        "tv_symbol": "US2000",
    },
    "BVSP": {
        "name": "巴西Bovespa",
        "market": "巴西",
        "region": "美洲市场",
        "country": "巴西",
        "currency": "BRL",
        "description": "巴西核心指数",
        "default_pe": 10.0,
        "earnings_growth": 4.0,
        "asset_type": "index",
        "yahoo_symbol": "^BVSP",
        "ak_symbol": None,
        "investing_symbol": "bvsp",
        "tv_symbol": "IBOV",
    },
    "TSX": {
        "name": "加拿大TSX",
        "market": "加拿大",
        "region": "美洲市场",
        "country": "加拿大",
        "currency": "CAD",
        "description": "加拿大综合指数",
        "default_pe": 16.0,
        "earnings_growth": 4.0,
        "asset_type": "index",
        "yahoo_symbol": "^GSPTSE",
        "ak_symbol": None,
        "investing_symbol": "tsx",
        "tv_symbol": "TSX",
    },

    # 欧洲市场
    "STOXX50": {
        "name": "欧洲STOXX50",
        "market": "欧洲",
        "region": "欧洲市场",
        "country": "欧洲",
        "currency": "EUR",
        "description": "欧元区蓝筹指数",
        "default_pe": 14.0,
        "earnings_growth": 4.0,
        "asset_type": "index",
        "yahoo_symbol": "^SX5E",
        "ak_symbol": None,
        "investing_symbol": "stoxx",
        "tv_symbol": "EU50",
        "hot": True,
    },
    "DAX": {
        "name": "德国DAX",
        "market": "德国",
        "region": "欧洲市场",
        "country": "德国",
        "currency": "EUR",
        "description": "德国核心指数",
        "default_pe": 15.0,
        "earnings_growth": 4.0,
        "asset_type": "index",
        "yahoo_symbol": "^GDAXI",
        "ak_symbol": None,
        "investing_symbol": "dax",
        "tv_symbol": "DAX",
        "hot": True,
    },
    "FTSE": {
        "name": "英国富时100",
        "market": "英国",
        "region": "欧洲市场",
        "country": "英国",
        "currency": "GBP",
        "description": "英国蓝筹指数",
        "default_pe": 12.0,
        "earnings_growth": 3.0,
        "asset_type": "index",
        "yahoo_symbol": "^UKX",
        "ak_symbol": None,
        "investing_symbol": "ftse",
        "tv_symbol": "UK100",
        "hot": True,
    },
    "CAC40": {
        "name": "法国CAC40",
        "market": "法国",
        "region": "欧洲市场",
        "country": "法国",
        "currency": "EUR",
        "description": "法国核心指数",
        "default_pe": 14.0,
        "earnings_growth": 4.0,
        "asset_type": "index",
        "yahoo_symbol": "^FCHI",
        "ak_symbol": None,
        "investing_symbol": "cac",
        "tv_symbol": "CAC40",
    },
    "SMI": {
        "name": "瑞士SMI",
        "market": "瑞士",
        "region": "欧洲市场",
        "country": "瑞士",
        "currency": "CHF",
        "description": "瑞士核心指数",
        "default_pe": 18.0,
        "earnings_growth": 4.0,
        "asset_type": "index",
        "yahoo_symbol": "^SSMI",
        "ak_symbol": None,
        "investing_symbol": "smi",
        "tv_symbol": "SMI",
    },
    "IBEX": {
        "name": "西班牙IBEX35",
        "market": "西班牙",
        "region": "欧洲市场",
        "country": "西班牙",
        "currency": "EUR",
        "description": "西班牙核心指数",
        "default_pe": 13.0,
        "earnings_growth": 4.0,
        "asset_type": "index",
        "yahoo_symbol": "^IBEX",
        "ak_symbol": None,
        "investing_symbol": "ibex",
        "tv_symbol": "IBEX",
    },
    "MIB": {
        "name": "意大利MIB",
        "market": "意大利",
        "region": "欧洲市场",
        "country": "意大利",
        "currency": "EUR",
        "description": "意大利核心指数",
        "default_pe": 14.0,
        "earnings_growth": 4.0,
        "asset_type": "index",
        "yahoo_symbol": "^FTSEMIB",
        "ak_symbol": None,
        "investing_symbol": "ftsemib",
        "tv_symbol": "ITA40",
    },
    "AEX": {
        "name": "荷兰AEX",
        "market": "荷兰",
        "region": "欧洲市场",
        "country": "荷兰",
        "currency": "EUR",
        "description": "荷兰核心指数",
        "default_pe": 15.0,
        "earnings_growth": 4.0,
        "asset_type": "index",
        "yahoo_symbol": "^AEX",
        "ak_symbol": None,
        "investing_symbol": "aex",
        "tv_symbol": "NED25",
    },

    # 亚洲市场
    "000300": {
        "name": "沪深300",
        "market": "A股",
        "region": "亚洲市场",
        "country": "中国",
        "currency": "CNY",
        "description": "A股蓝筹代表",
        "default_pe": 13.0,
        "earnings_growth": 6.0,
        "asset_type": "index",
        "yahoo_symbol": "000300.SS",
        "ak_symbol": "沪深300指数",
        "investing_symbol": None,
        "tv_symbol": "SHA:000300",
        "hot": True,
    },
    "000016": {
        "name": "上证50",
        "market": "A股",
        "region": "亚洲市场",
        "country": "中国",
        "currency": "CNY",
        "description": "超大盘蓝筹",
        "default_pe": 11.0,
        "earnings_growth": 5.0,
        "asset_type": "index",
        "yahoo_symbol": "000016.SS",
        "ak_symbol": "上证50",
        "investing_symbol": None,
        "tv_symbol": "SHA:000016",
    },
    "000905": {
        "name": "中证500",
        "market": "A股",
        "region": "亚洲市场",
        "country": "中国",
        "currency": "CNY",
        "description": "中盘成长",
        "default_pe": 20.0,
        "earnings_growth": 7.0,
        "asset_type": "index",
        "yahoo_symbol": "000905.SS",
        "ak_symbol": "中证500指数",
        "investing_symbol": None,
        "tv_symbol": "SHA:000905",
        "hot": True,
    },
    "000852": {
        "name": "中证1000",
        "market": "A股",
        "region": "亚洲市场",
        "country": "中国",
        "currency": "CNY",
        "description": "小盘活跃",
        "default_pe": 25.0,
        "earnings_growth": 8.0,
        "asset_type": "index",
        "yahoo_symbol": "000852.SS",
        "ak_symbol": "中证1000指数",
        "investing_symbol": None,
        "tv_symbol": "SHA:000852",
    },
    "399006": {
        "name": "创业板指",
        "market": "A股",
        "region": "亚洲市场",
        "country": "中国",
        "currency": "CNY",
        "description": "成长科技",
        "default_pe": 30.0,
        "earnings_growth": 10.0,
        "asset_type": "index",
        "yahoo_symbol": "399006.SZ",
        "ak_symbol": "创业板指数",
        "investing_symbol": None,
        "tv_symbol": "SZH:399006",
        "hot": True,
    },
    "000001": {
        "name": "上证综指",
        "market": "A股",
        "region": "亚洲市场",
        "country": "中国",
        "currency": "CNY",
        "description": "A股全市场",
        "default_pe": 14.0,
        "earnings_growth": 6.0,
        "asset_type": "index",
        "yahoo_symbol": "000001.SS",
        "ak_symbol": "上证综合指数",
        "investing_symbol": None,
        "tv_symbol": "SHA:000001",
    },
    "399001": {
        "name": "深证成指",
        "market": "A股",
        "region": "亚洲市场",
        "country": "中国",
        "currency": "CNY",
        "description": "深市核心指数",
        "default_pe": 22.0,
        "earnings_growth": 8.0,
        "asset_type": "index",
        "yahoo_symbol": "399001.SZ",
        "ak_symbol": None,
        "investing_symbol": None,
        "tv_symbol": "SZH:399001",
    },
    "HSI": {
        "name": "恒生指数",
        "market": "港股",
        "region": "亚洲市场",
        "country": "香港",
        "currency": "HKD",
        "description": "港股蓝筹指数",
        "default_pe": 10.0,
        "earnings_growth": 5.0,
        "asset_type": "index",
        "yahoo_symbol": "^HSI",
        "ak_symbol": None,
        "investing_symbol": "hsi",
        "tv_symbol": "HKEX:HSI",
        "hot": True,
    },
    "N225": {
        "name": "日经225",
        "market": "日本",
        "region": "亚洲市场",
        "country": "日本",
        "currency": "JPY",
        "description": "日本核心指数",
        "default_pe": 20.0,
        "earnings_growth": 5.0,
        "asset_type": "index",
        "yahoo_symbol": "^N225",
        "ak_symbol": None,
        "investing_symbol": "nikkei",
        "tv_symbol": "JPN225",
        "hot": True,
    },
    "KOSPI": {
        "name": "韩国KOSPI",
        "market": "韩国",
        "region": "亚洲市场",
        "country": "韩国",
        "currency": "KRW",
        "description": "韩国综合指数",
        "default_pe": 13.0,
        "earnings_growth": 5.0,
        "asset_type": "index",
        "yahoo_symbol": "^KS11",
        "ak_symbol": None,
        "investing_symbol": "kospi",
        "tv_symbol": "KOR200",
    },
    "SENSEX": {
        "name": "印度SENSEX",
        "market": "印度",
        "region": "亚洲市场",
        "country": "印度",
        "currency": "INR",
        "description": "印度大盘指数",
        "default_pe": 23.0,
        "earnings_growth": 8.0,
        "asset_type": "index",
        "yahoo_symbol": "^BSESN",
        "ak_symbol": None,
        "investing_symbol": "sensex",
        "tv_symbol": "IND50",
        "hot": True,
    },
    "NIFTY": {
        "name": "印度NIFTY 50",
        "market": "印度",
        "region": "亚洲市场",
        "country": "印度",
        "currency": "INR",
        "description": "印度NIFTY指数",
        "default_pe": 22.0,
        "earnings_growth": 8.0,
        "asset_type": "index",
        "yahoo_symbol": "^NSEI",
        "ak_symbol": None,
        "investing_symbol": "nifty50",
        "tv_symbol": "INDIA50",
    },
    "STI": {
        "name": "新加坡海峡时报",
        "market": "新加坡",
        "region": "亚洲市场",
        "country": "新加坡",
        "currency": "SGD",
        "description": "新加坡核心指数",
        "default_pe": 14.0,
        "earnings_growth": 4.0,
        "asset_type": "index",
        "yahoo_symbol": "^STI",
        "ak_symbol": None,
        "investing_symbol": "sti",
        "tv_symbol": "SGP",
    },
    "AS51": {
        "name": "澳洲ASX 200",
        "market": "澳洲",
        "region": "亚洲市场",
        "country": "澳大利亚",
        "currency": "AUD",
        "description": "澳大利亚核心指数",
        "default_pe": 15.0,
        "earnings_growth": 5.0,
        "asset_type": "index",
        "yahoo_symbol": "^AXJO",
        "ak_symbol": None,
        "investing_symbol": "asx200",
        "tv_symbol": "AU200",
    },
}

# 全球热门股票配置
GLOBAL_STOCKS: list[dict[str, Any]] = [
    # 美股科技巨头
    {"code": "AAPL", "name": "苹果", "market": "美股", "region": "美洲市场", "country": "美国", "currency": "USD", "description": "消费电子巨头", "default_pe": 28.0, "earnings_growth": 7.0, "asset_type": "stock", "yahoo_symbol": "AAPL", "tv_symbol": "AAPL", "hot": True},
    {"code": "MSFT", "name": "微软", "market": "美股", "region": "美洲市场", "country": "美国", "currency": "USD", "description": "软件云计算龙头", "default_pe": 32.0, "earnings_growth": 10.0, "asset_type": "stock", "yahoo_symbol": "MSFT", "tv_symbol": "MSFT", "hot": True},
    {"code": "NVDA", "name": "英伟达", "market": "美股", "region": "美洲市场", "country": "美国", "currency": "USD", "description": "AI芯片龙头", "default_pe": 45.0, "earnings_growth": 15.0, "asset_type": "stock", "yahoo_symbol": "NVDA", "tv_symbol": "NVDA", "hot": True},
    {"code": "TSLA", "name": "特斯拉", "market": "美股", "region": "美洲市场", "country": "美国", "currency": "USD", "description": "电动汽车龙头", "default_pe": 50.0, "earnings_growth": 12.0, "asset_type": "stock", "yahoo_symbol": "TSLA", "tv_symbol": "TSLA", "hot": True},
    {"code": "AMZN", "name": "亚马逊", "market": "美股", "region": "美洲市场", "country": "美国", "currency": "USD", "description": "电商云计算巨头", "default_pe": 35.0, "earnings_growth": 10.0, "asset_type": "stock", "yahoo_symbol": "AMZN", "tv_symbol": "AMZN", "hot": True},
    {"code": "GOOGL", "name": "谷歌A", "market": "美股", "region": "美洲市场", "country": "美国", "currency": "USD", "description": "搜索引擎巨头", "default_pe": 26.0, "earnings_growth": 8.0, "asset_type": "stock", "yahoo_symbol": "GOOGL", "tv_symbol": "GOOGL", "hot": True},
    {"code": "META", "name": "Meta Platforms", "market": "美股", "region": "美洲市场", "country": "美国", "currency": "USD", "description": "社交媒体巨头", "default_pe": 24.0, "earnings_growth": 8.0, "asset_type": "stock", "yahoo_symbol": "META", "tv_symbol": "META", "hot": True},
    {"code": "BRK-B", "name": "伯克希尔哈撒韦B", "market": "美股", "region": "美洲市场", "country": "美国", "currency": "USD", "description": "巴菲特投资公司", "default_pe": 18.0, "earnings_growth": 6.0, "asset_type": "stock", "yahoo_symbol": "BRK-B", "tv_symbol": "BRK.B"},
    {"code": "JPM", "name": "摩根大通", "market": "美股", "region": "美洲市场", "country": "美国", "currency": "USD", "description": "美国银行业龙头", "default_pe": 11.0, "earnings_growth": 6.0, "asset_type": "stock", "yahoo_symbol": "JPM", "tv_symbol": "JPM"},
    {"code": "V", "name": "Visa", "market": "美股", "region": "美洲市场", "country": "美国", "currency": "USD", "description": "支付网络巨头", "default_pe": 28.0, "earnings_growth": 10.0, "asset_type": "stock", "yahoo_symbol": "V", "tv_symbol": "V"},
    {"code": "MA", "name": "万事达卡", "market": "美股", "region": "美洲市场", "country": "美国", "currency": "USD", "description": "支付网络龙头", "default_pe": 32.0, "earnings_growth": 11.0, "asset_type": "stock", "yahoo_symbol": "MA", "tv_symbol": "MA"},
    {"code": "JNJ", "name": "强生", "market": "美股", "region": "美洲市场", "country": "美国", "currency": "USD", "description": "医疗保健巨头", "default_pe": 16.0, "earnings_growth": 5.0, "asset_type": "stock", "yahoo_symbol": "JNJ", "tv_symbol": "JNJ"},
    {"code": "PG", "name": "宝洁", "market": "美股", "region": "美洲市场", "country": "美国", "currency": "USD", "description": "消费品巨头", "default_pe": 25.0, "earnings_growth": 4.0, "asset_type": "stock", "yahoo_symbol": "PG", "tv_symbol": "PG"},
    {"code": "KO", "name": "可口可乐", "market": "美股", "region": "美洲市场", "country": "美国", "currency": "USD", "description": "饮料巨头", "default_pe": 24.0, "earnings_growth": 4.0, "asset_type": "stock", "yahoo_symbol": "KO", "tv_symbol": "KO"},
    {"code": "DIS", "name": "迪士尼", "market": "美股", "region": "美洲市场", "country": "美国", "currency": "USD", "description": "娱乐传媒巨头", "default_pe": 35.0, "earnings_growth": 8.0, "asset_type": "stock", "yahoo_symbol": "DIS", "tv_symbol": "DIS"},

    # 欧洲股票
    {"code": "ASML", "name": "阿斯麦", "market": "荷兰", "region": "欧洲市场", "country": "荷兰", "currency": "EUR", "description": "光刻机龙头", "default_pe": 38.0, "earnings_growth": 12.0, "asset_type": "stock", "yahoo_symbol": "ASML.AS", "tv_symbol": "EPA:ASML", "hot": True},
    {"code": "SAP", "name": "SAP", "market": "德国", "region": "欧洲市场", "country": "德国", "currency": "EUR", "description": "企业软件龙头", "default_pe": 30.0, "earnings_growth": 8.0, "asset_type": "stock", "yahoo_symbol": "SAP.DE", "tv_symbol": "DB:SAP"},
    {"code": "NESN", "name": "雀巢", "market": "瑞士", "region": "欧洲市场", "country": "瑞士", "currency": "CHF", "description": "食品饮料巨头", "default_pe": 26.0, "earnings_growth": 4.0, "asset_type": "stock", "yahoo_symbol": "NESN.SW", "tv_symbol": "SWX:NESN"},
    {"code": "HSBA", "name": "汇丰控股", "market": "英国", "region": "欧洲市场", "country": "英国", "currency": "GBP", "description": "国际银行龙头", "default_pe": 9.0, "earnings_growth": 4.0, "asset_type": "stock", "yahoo_symbol": "HSBA.L", "tv_symbol": "LSE:HSBA"},
    {"code": "ULVR", "name": "联合利华", "market": "英国", "region": "欧洲市场", "country": "英国", "currency": "GBP", "description": "消费品巨头", "default_pe": 22.0, "earnings_growth": 4.0, "asset_type": "stock", "yahoo_symbol": "ULVR.L", "tv_symbol": "LSE:ULVR"},
    {"code": "MC", "name": "路易威登", "market": "法国", "region": "欧洲市场", "country": "法国", "currency": "EUR", "description": "奢侈品龙头", "default_pe": 28.0, "earnings_growth": 8.0, "asset_type": "stock", "yahoo_symbol": "MC.PA", "tv_symbol": "EPA:MC", "hot": True},
    {"code": "OR", "name": "欧莱雅", "market": "法国", "region": "欧洲市场", "country": "法国", "currency": "EUR", "description": "化妆品巨头", "default_pe": 30.0, "earnings_growth": 7.0, "asset_type": "stock", "yahoo_symbol": "OR.PA", "tv_symbol": "EPA:OR"},
    {"code": "BMW", "name": "宝马", "market": "德国", "region": "欧洲市场", "country": "德国", "currency": "EUR", "description": "豪华汽车制造商", "default_pe": 8.0, "earnings_growth": 5.0, "asset_type": "stock", "yahoo_symbol": "BMW.DE", "tv_symbol": "DB:BMW"},
    {"code": "ENI", "name": "埃尼集团", "market": "意大利", "region": "欧洲市场", "country": "意大利", "currency": "EUR", "description": "能源巨头", "default_pe": 6.0, "earnings_growth": 3.0, "asset_type": "stock", "yahoo_symbol": "ENI.MI", "tv_symbol": "BIT:ENI"},
    {"code": "INGA", "name": "ING集团", "market": "荷兰", "region": "欧洲市场", "country": "荷兰", "currency": "EUR", "description": "金融服务集团", "default_pe": 7.0, "earnings_growth": 4.0, "asset_type": "stock", "yahoo_symbol": "INGA.AS", "tv_symbol": "EPA:INGA"},

    # 港股
    {"code": "0700.HK", "name": "腾讯控股", "market": "港股", "region": "亚洲市场", "country": "香港", "currency": "HKD", "description": "互联网巨头", "default_pe": 18.0, "earnings_growth": 8.0, "asset_type": "stock", "yahoo_symbol": "0700.HK", "tv_symbol": "HKEX:0700", "hot": True},
    {"code": "9988.HK", "name": "阿里巴巴-W", "market": "港股", "region": "亚洲市场", "country": "香港", "currency": "HKD", "description": "电商巨头", "default_pe": 15.0, "earnings_growth": 7.0, "asset_type": "stock", "yahoo_symbol": "9988.HK", "tv_symbol": "HKEX:9988", "hot": True},
    {"code": "3690.HK", "name": "美团-W", "market": "港股", "region": "亚洲市场", "country": "香港", "currency": "HKD", "description": "生活服务平台", "default_pe": 35.0, "earnings_growth": 10.0, "asset_type": "stock", "yahoo_symbol": "3690.HK", "tv_symbol": "HKEX:3690"},
    {"code": "9618.HK", "name": "京东集团", "market": "港股", "region": "亚洲市场", "country": "香港", "currency": "HKD", "description": "电商巨头", "default_pe": 16.0, "earnings_growth": 8.0, "asset_type": "stock", "yahoo_symbol": "9618.HK", "tv_symbol": "HKEX:9618"},
    {"code": "1024.HK", "name": "快手-W", "market": "港股", "region": "亚洲市场", "country": "香港", "currency": "HKD", "description": "短视频平台", "default_pe": 25.0, "earnings_growth": 12.0, "asset_type": "stock", "yahoo_symbol": "1024.HK", "tv_symbol": "HKEX:1024"},
    {"code": "0941.HK", "name": "中国移动", "market": "港股", "region": "亚洲市场", "country": "香港", "currency": "HKD", "description": "通信运营商", "default_pe": 8.0, "earnings_growth": 3.0, "asset_type": "stock", "yahoo_symbol": "0941.HK", "tv_symbol": "HKEX:0941"},
    {"code": "1299.HK", "name": "友邦保险", "market": "港股", "region": "亚洲市场", "country": "香港", "currency": "HKD", "description": "保险巨头", "default_pe": 12.0, "earnings_growth": 5.0, "asset_type": "stock", "yahoo_symbol": "1299.HK", "tv_symbol": "HKEX:1299"},
    {"code": "0883.HK", "name": "中海油", "market": "港股", "region": "亚洲市场", "country": "香港", "currency": "HKD", "description": "能源巨头", "default_pe": 6.0, "earnings_growth": 4.0, "asset_type": "stock", "yahoo_symbol": "0883.HK", "tv_symbol": "HKEX:0883"},

    # 日本股票
    {"code": "7203.T", "name": "丰田汽车", "market": "日本", "region": "亚洲市场", "country": "日本", "currency": "JPY", "description": "汽车制造商", "default_pe": 9.0, "earnings_growth": 4.0, "asset_type": "stock", "yahoo_symbol": "7203.T", "tv_symbol": "TSE:7203", "hot": True},
    {"code": "6758.T", "name": "索尼集团", "market": "日本", "region": "亚洲市场", "country": "日本", "currency": "JPY", "description": "电子娱乐巨头", "default_pe": 16.0, "earnings_growth": 6.0, "asset_type": "stock", "yahoo_symbol": "6758.T", "tv_symbol": "TSE:6758"},
    {"code": "8035.T", "name": "东京电子", "market": "日本", "region": "亚洲市场", "country": "日本", "currency": "JPY", "description": "半导体设备", "default_pe": 22.0, "earnings_growth": 10.0, "asset_type": "stock", "yahoo_symbol": "8035.T", "tv_symbol": "TSE:8035"},
    {"code": "9984.T", "name": "软银集团", "market": "日本", "region": "亚洲市场", "country": "日本", "currency": "JPY", "description": "投资控股", "default_pe": 18.0, "earnings_growth": 8.0, "asset_type": "stock", "yahoo_symbol": "9984.T", "tv_symbol": "TSE:9984"},

    # A股
    {"code": "600519", "name": "贵州茅台", "market": "A股", "region": "亚洲市场", "country": "中国", "currency": "CNY", "description": "白酒龙头", "default_pe": 25.0, "earnings_growth": 6.0, "asset_type": "stock", "yahoo_symbol": "600519.SS", "tv_symbol": "SHA:600519", "hot": True},
    {"code": "000858", "name": "五粮液", "market": "A股", "region": "亚洲市场", "country": "中国", "currency": "CNY", "description": "白酒巨头", "default_pe": 20.0, "earnings_growth": 6.0, "asset_type": "stock", "yahoo_symbol": "000858.SZ", "tv_symbol": "SZH:000858"},
    {"code": "601318", "name": "中国平安", "market": "A股", "region": "亚洲市场", "country": "中国", "currency": "CNY", "description": "保险金融", "default_pe": 10.0, "earnings_growth": 4.0, "asset_type": "stock", "yahoo_symbol": "601318.SS", "tv_symbol": "SHA:601318"},
    {"code": "600036", "name": "招商银行", "market": "A股", "region": "亚洲市场", "country": "中国", "currency": "CNY", "description": "零售银行", "default_pe": 8.0, "earnings_growth": 4.0, "asset_type": "stock", "yahoo_symbol": "600036.SS", "tv_symbol": "SHA:600036"},
    {"code": "000333", "name": "美的集团", "market": "A股", "region": "亚洲市场", "country": "中国", "currency": "CNY", "description": "家电巨头", "default_pe": 15.0, "earnings_growth": 5.0, "asset_type": "stock", "yahoo_symbol": "000333.SZ", "tv_symbol": "SZH:000333"},
    {"code": "300750", "name": "宁德时代", "market": "A股", "region": "亚洲市场", "country": "中国", "currency": "CNY", "description": "电池龙头", "default_pe": 24.0, "earnings_growth": 10.0, "asset_type": "stock", "yahoo_symbol": "300750.SZ", "tv_symbol": "SZH:300750"},
    {"code": "002594", "name": "比亚迪", "market": "A股", "region": "亚洲市场", "country": "中国", "currency": "CNY", "description": "新能源汽车", "default_pe": 22.0, "earnings_growth": 9.0, "asset_type": "stock", "yahoo_symbol": "002594.SZ", "tv_symbol": "SZH:002594"},
    {"code": "600276", "name": "恒瑞医药", "market": "A股", "region": "亚洲市场", "country": "中国", "currency": "CNY", "description": "医药龙头", "default_pe": 35.0, "earnings_growth": 9.0, "asset_type": "stock", "yahoo_symbol": "600276.SS", "tv_symbol": "SHA:600276"},
]

# 全球ETF配置
GLOBAL_ETF: list[dict[str, Any]] = [
    # A股基金
    {"code": "510300", "name": "沪深300ETF", "market": "基金", "region": "亚洲市场", "country": "中国", "currency": "CNY", "description": "追踪沪深300", "default_pe": 13.0, "earnings_growth": 6.0, "asset_type": "fund", "yahoo_symbol": "510300.SS", "tv_symbol": "SHA:510300", "hot": True},
    {"code": "510050", "name": "上证50ETF", "market": "基金", "region": "亚洲市场", "country": "中国", "currency": "CNY", "description": "追踪上证50", "default_pe": 11.0, "earnings_growth": 5.0, "asset_type": "fund", "yahoo_symbol": "510050.SS", "tv_symbol": "SHA:510050"},
    {"code": "510500", "name": "中证500ETF", "market": "基金", "region": "亚洲市场", "country": "中国", "currency": "CNY", "description": "追踪中证500", "default_pe": 20.0, "earnings_growth": 7.0, "asset_type": "fund", "yahoo_symbol": "510500.SS", "tv_symbol": "SHA:510500"},
    {"code": "159915", "name": "创业板ETF", "market": "基金", "region": "亚洲市场", "country": "中国", "currency": "CNY", "description": "追踪创业板", "default_pe": 30.0, "earnings_growth": 10.0, "asset_type": "fund", "yahoo_symbol": "159915.SZ", "tv_symbol": "SZH:159915"},

    # QDII基金（投资海外）
    {"code": "513500", "name": "标普500ETF", "market": "基金", "region": "亚洲市场", "country": "中国", "currency": "CNY", "description": "投资标普500", "default_pe": 22.0, "earnings_growth": 7.0, "asset_type": "fund", "yahoo_symbol": "513500.SS", "tv_symbol": "SHA:513500", "hot": True},
    {"code": "513100", "name": "纳指ETF", "market": "基金", "region": "亚洲市场", "country": "中国", "currency": "CNY", "description": "投资纳斯达克100", "default_pe": 28.0, "earnings_growth": 10.0, "asset_type": "fund", "yahoo_symbol": "513100.SS", "tv_symbol": "SHA:513100", "hot": True},
    {"code": "513030", "name": "德国ETF", "market": "基金", "region": "亚洲市场", "country": "中国", "currency": "CNY", "description": "投资德国DAX", "default_pe": 15.0, "earnings_growth": 4.0, "asset_type": "fund", "yahoo_symbol": "513030.SS", "tv_symbol": "SHA:513030"},
    {"code": "513650", "name": "恒生科技ETF", "market": "基金", "region": "亚洲市场", "country": "中国", "currency": "CNY", "description": "投资恒生科技", "default_pe": 25.0, "earnings_growth": 10.0, "asset_type": "fund", "yahoo_symbol": "513650.SS", "tv_symbol": "SHA:513650"},
    {"code": "164906", "name": "中国互联LOF", "market": "基金", "region": "亚洲市场", "country": "中国", "currency": "CNY", "description": "投资中概互联网", "default_pe": 18.0, "earnings_growth": 8.0, "asset_type": "fund", "yahoo_symbol": "164906.SZ", "tv_symbol": "SZH:164906"},

    # 美股ETF
    {"code": "SPY", "name": "标普500 ETF", "market": "美股ETF", "region": "美洲市场", "country": "美国", "currency": "USD", "description": "追踪标普500", "default_pe": 22.0, "earnings_growth": 7.0, "asset_type": "fund", "yahoo_symbol": "SPY", "tv_symbol": "AMEX:SPY", "hot": True},
    {"code": "QQQ", "name": "纳斯达克100 ETF", "market": "美股ETF", "region": "美洲市场", "country": "美国", "currency": "USD", "description": "追踪纳斯达克100", "default_pe": 28.0, "earnings_growth": 10.0, "asset_type": "fund", "yahoo_symbol": "QQQ", "tv_symbol": "AMEX:QQQ", "hot": True},
    {"code": "VOO", "name": "Vanguard标普500ETF", "market": "美股ETF", "region": "美洲市场", "country": "美国", "currency": "USD", "description": "Vanguard标普500", "default_pe": 22.0, "earnings_growth": 7.0, "asset_type": "fund", "yahoo_symbol": "VOO", "tv_symbol": "AMEX:VOO"},
    {"code": "VTI", "name": "Vanguard总市场ETF", "market": "美股ETF", "region": "美洲市场", "country": "美国", "currency": "USD", "description": "全市场ETF", "default_pe": 20.0, "earnings_growth": 6.0, "asset_type": "fund", "yahoo_symbol": "VTI", "tv_symbol": "AMEX:VTI"},
    {"code": "IWM", "name": "罗素2000 ETF", "market": "美股ETF", "region": "美洲市场", "country": "美国", "currency": "USD", "description": "小盘股ETF", "default_pe": 24.0, "earnings_growth": 6.0, "asset_type": "fund", "yahoo_symbol": "IWM", "tv_symbol": "AMEX:IWM"},
    {"code": "VWO", "name": "Vanguard新兴市场", "market": "美股ETF", "region": "美洲市场", "country": "美国", "currency": "USD", "description": "新兴市场ETF", "default_pe": 12.0, "earnings_growth": 7.0, "asset_type": "fund", "yahoo_symbol": "VWO", "tv_symbol": "AMEX:VWO"},
    {"code": "EFA", "name": "iShares发达市场", "market": "美股ETF", "region": "美洲市场", "country": "美国", "currency": "USD", "description": "发达市场ETF", "default_pe": 16.0, "earnings_growth": 5.0, "asset_type": "fund", "yahoo_symbol": "EFA", "tv_symbol": "AMEX:EFA"},
    {"code": "EEM", "name": "iShares新兴市场", "market": "美股ETF", "region": "美洲市场", "country": "美国", "currency": "USD", "description": "新兴市场ETF", "default_pe": 13.0, "earnings_growth": 8.0, "asset_type": "fund", "yahoo_symbol": "EEM", "tv_symbol": "AMEX:EEM"},

    # 港股ETF
    {"code": "2800.HK", "name": "盈富基金", "market": "港股ETF", "region": "亚洲市场", "country": "香港", "currency": "HKD", "description": "追踪恒生指数", "default_pe": 10.0, "earnings_growth": 5.0, "asset_type": "fund", "yahoo_symbol": "2800.HK", "tv_symbol": "HKEX:2800", "hot": True},
    {"code": "3033.HK", "name": "南方恒生科技", "market": "港股ETF", "region": "亚洲市场", "country": "香港", "currency": "HKD", "description": "追踪恒生科技", "default_pe": 25.0, "earnings_growth": 10.0, "asset_type": "fund", "yahoo_symbol": "3033.HK", "tv_symbol": "HKEX:3033"},
    {"code": "7226.HK", "name": "恒生科技ETF", "market": "港股ETF", "region": "亚洲市场", "country": "香港", "currency": "HKD", "description": "追踪恒生科技", "default_pe": 25.0, "earnings_growth": 10.0, "asset_type": "fund", "yahoo_symbol": "7226.HK", "tv_symbol": "HKEX:7226"},
]

# 基金代码前缀
FUND_PREFIXES = ("159", "160", "161", "162", "164", "510", "511", "512", "513", "515", "516", "517", "518", "588")
